datasets:
  input:
    type: file
    path: /Users/vareeshbainwala/.docetl/files/merged_file.json
    source: local
default_model: gpt-4o-mini
optimizer_config:
  force_decompose: true
operations:
  - type: map
    name: Map_Research_details
    prompt: "Analyze the following personal statement and recommendation letters for {{ input.ID }}:\n\n      Personal Statement:\n      {{ input.Application.SOP }}\n\n      Recommendation Letters:\n      {{ input.Application.Recommendation_Letters }}\n\n      Task:\n      Extract the main research experience discussed in the personal statement, focusing on:\n\n        •\tProjects and research done in the past.\n        •\tTechnical skills applied by the applicant in the projects.\n        •\tA detailed description of each project/research.\n        •\tCollaboration skills demonstrated.\n\n      Organize the extracted details by categorizing them under the different areas of research provided in {{ input.Application.Research_Areas }}. For each research area, create a dictionary containing all the associated projects and their respective details. Match and include relevant information from the recommendation letters that corroborates the research experience."
    output:
      schema:
        research: >-
          list[{area: string, project: string, description: string,
          collaboration: string, recommendation: string, skills: string,
          applicant_id: string}]
    sample: 2
  - type: unnest
    name: Unnest Research
    unnest_key: research
    recursive: true
  - type: reduce
    name: Untitled Reduce 31
    prompt: >
      You have the research area for each project {{ reduce_key[0] }} and the
      corresponding applicant detail {{ reduce_key[1] }}

      For each pair of {{reduce_key[0]}}, {{reduce_key[1]}} provide a summary of
      the {{inputs.project}} for each applicant based on the following
      information


      {% for input in inputs %}

      Project : {{ input.project }}

      description: {{input.description}}

      {% endfor %}
    output:
      schema:
        report: string
    shouldOptimizeResult: >-
      The outputs across the examples do not include a comprehensive summary of
      projects and research experiences from the personal statement and
      recommendation letters, primarily due to the inputs being placeholders and
      lacking real data. Therefore, the evaluation of integration with
      recommendation letters cannot be fully verified.

      Technical and collaboration skills have been explicitly identified within
      the project descriptions in both cases, demonstrating appropriate matching
      of skills to projects.

      The alignment between research areas and projects seems consistent within
      the fictional context provided, but the lack of actual personal statement
      content means that the linkage cannot be substantively validated against
      real inputs.

      Recommendation letters detail is present and aligns with projects, but
      again, the corroboration aspect is limited by the N/A placeholders in the
      sample inputs. There is no discussion of potential discrepancies between
      personal statements and letters due to lack of actual content.


      Here are some improvements that may help:

      Ensure that the sample inputs contain detailed information not labeled as
      'N/A' to allow a thorough assessment of the operation's ability to extract
      and correlate data between personal statements and recommendation letters.

      Test the operation with real data inputs where full personal statements
      and letters are available to enable validation of the integration aspect.

      Verify the consistency of extracted project details across different
      sources for more robust cross-verification.

      Consider scenarios where recommendation letters contradict the personal
      statement and evaluate how the system handles such inconsistencies.
    reduce_key:
      - area
      - applicant_id
pipeline:
  steps:
    - name: data_processing
      input: input
      operations:
        - Map_Research_details
        - Unnest Research
        - Untitled Reduce 31
  output:
    type: file
    path: >-
      grad_school_app_summaries_ui.json
    intermediate_dir: >-
      /Users/vareeshbainwala/.docetl/pipelines/Grad_reviewer_pipeline/intermediates
