datasets:
  input:
    type: file
    path: /Users/vareeshbainwala/.docetl/files/input_document_docetl.json
    source: local
default_model: gpt-4o-mini
optimizer_config:
  force_decompose: true
operations:
  - type: map
    name: Map_Research_details
    prompt: "Analyze the following personal statement and resume for {{ input.ID }}:\n\n      Personal Statement:\n      {{ input.Application.SOP }}\n\n      Resume:\n      {{ input.Application.Resume }}\n\n      Task:\n      Extract the main research experience discussed in the personal statement and the resume.\n      While selecting pay special focus to the below criteria\n\n        •\tProjects and research done in the past.\n        •\tTechnical skills applied by the applicant in the projects.\n        •\tA detailed description of each project/research.\n        •\tFor each project classify it in a research area among the following : ['Artificial Intelligence','Augmented Reality and Virtual Reality','Biomedical Informatics and Computational Biology',\n                                'Computer Architecture','Databases and Data Management','Design Automation','Embedded Systems','Graphics',\n                                'Human–Computer Interaction','Information Retrieval','Machine Learning','Machine Learning Systems','Natural Language Processing',\n                                'Network Systems','Programming Languages','Robotics','Security and Privacy','Software Engineering','Software Systems',\n                                'Speech Language Processing','Theory','Vision']\n    Additionally filter the resume to find previous education and publications if any. \n    Organize the output for each applicant using the {{input.ID}}\n"
    output:
      schema:
        ID: string
        Experience: >-
          list[{Project: string, Description: string, Skills: string,
          Research_Area: string}]
        Education: string
        Publications: string
    shouldOptimizeResult: >-
      The outputs for the sample inputs seem accurate in terms of extracting
      research experiences, but details about the descriptions and skills
      mentioned in the personal statement or resume are missing, as only 'N/A'
      is provided. Without the actual content, we cannot validate if the
      descriptions and skills were captured accurately.

      The projects have been classified into the specified research areas, such
      as 'Machine Learning', 'Biomedical Informatics and Computational Biology',
      etc., correctly.

      Previous education and publication details are extracted accurately and
      presented consistently with the applicant's ID format.


      Here are some improvements that may help:

      Include the actual content of the personal statement and resume in order
      to assess if the extraction and classification align with the details
      specified in those documents.

      Ensure accurate mapping by showing detailed descriptions and listing
      technical skills applied for each project that should come directly from
      the applicant's documents.
    sample: 59
pipeline:
  steps:
    - name: data_processing
      input: input
      operations:
        - Map_Research_details
  output:
    type: file
    path: >-
      /Users/vareeshbainwala/.docetl/pipelines/outputs/Grad_reviewer_pipeline.json
    intermediate_dir: >-
      /Users/vareeshbainwala/.docetl/pipelines/Grad_reviewer_pipeline/intermediates
