datasets:
  apps:
    path: json_documents/filtered_171318992.json
    type: file

default_model: gpt-4o-mini

operations:
  - name: extract_important_attributes
    type: map
    output:
      schema:
        attributes: list[str]
    prompt: |
      Analyze the following transcript of a student's grad school application:
      {{ input.SOP }}
      Extract and list all important attributes in the student application.
      

pipeline:
  steps:
    - name: grad_school_app_extraction
      input: apps
      operations:
        - extract_important_attributes
  output:
    type: file
    path: grad_school_app_summaries.json
    intermediate_dir: intermediate_results